### ISSUE TITLE
using in npm, says JSONFormatter missing

### ISSUE THREAD

**Issue by pangoyal** [mohsen1/json-schema-view-js#18]
Hey,

So I am using this library in node and when I give it an **enum**, it fails saying JSONFormatter is not defined.
node version 7.7.4
npm version 4.4.4

**Comment by mohsen1** [comment]
You also need [JSONFormatter](https://github.com/mohsen1/json-formatter-js) to be installed and available globally.

**Comment by pangoyal** [comment]
@mohsen1 JSONFormatter is a dependency of this module and not mine, so this module should make it available.

**Comment by meghnaraok** [comment]
@mohsen1 I cannot install the package globally as I do not have privileges, what else can I do. I already have it installed in node_modules but still get this issue

**Comment by mohsen1** [comment]
globally I mean in browser global. You just need to include JSON formatter too

**Comment by meghnaraok** [comment]
Include it where?
I have done this:
import JSONFormatter from 'json-formatter-js';
import JSONSchemaView from 'json-schema-view-js';
but it doesnt work. Im sorry but it will be helpful if you give me an example.

**Comment by mohsen1** [comment]
Not sure about your setup. Check out the demo folder as an example:

you can try this too:
```js
import JSONFormatter from 'json-formatter-js';
window.JSONFormatter = JSONFormatter;
```

**Comment by pangoyal** [comment]
patched in PR https://github.com/mohsen1/json-schema-view-js/pull/21
