### ISSUE TITLE
enums aren't shown if under an array

### ISSUE THREAD

**Issue by pangoyal** [mohsen1/json-schema-view-js#20]
the enums are shown as in
`{
            type: 'string',
            enum: ['one', 'two', 'three']
}`
But not in
`{  "type": "array", 
    "items": {
      "type":"string",
      "enum": ["one", "two", "three"]
    }
}`

**Comment by mohsen1** [comment]
You need JSON Formatter dependency

**Comment by pangoyal** [comment]
I do have the JSON Formatter dependency I added explicitly.

**Comment by pangoyal** [comment]
patched in PR https://github.com/mohsen1/json-schema-view-js/pull/21
