### ISSUE TITLE
JSONFormatter should be a dependency not devDependency

### ISSUE THREAD

**Issue by chrisdudley** [mohsen1/json-schema-view-js#23]
JSONFormatter is a runtime dependency of json-schema-view-js and so should be listed as such instead of being only a devDependency.

"dependencies are required to run, devDependencies only to develop, e.g.: unit tests, Coffeescript to Javascript transpilation, minification, ."

**Comment by mohsen1** [comment]
good catch! PR to fix it is welcome!

**Comment by chrisdudley** [comment]
https://github.com/mohsen1/json-schema-view-js/pull/24 :-)

**Comment by chrisdudley** [comment]
Thanks for merging. Could I be cheeky and ask for an updated release to npm with the fix in please?

**Comment by chrisdudley** [comment]
Lol - just saw you've done that. Thank you!
